/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FileId = bigint;
export interface FileInfo {
  'id' : FileId,
  'token' : FileToken,
  'name' : string,
  'expiryTime' : [] | [Timestamp],
  'size' : bigint,
  'downloadCount' : bigint,
  'uploadTime' : Timestamp,
}
export interface FileInfoAdmin {
  'id' : FileId,
  'token' : FileToken,
  'name' : string,
  'expiryTime' : [] | [Timestamp],
  'size' : bigint,
  'uploader' : Principal,
  'downloadCount' : bigint,
  'uploadTime' : Timestamp,
}
export type FileToken = string;
export interface PlatformCounts {
  'totalFiles' : bigint,
  'totalBytes' : bigint,
  'totalDownloads' : bigint,
}
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'downloadFile' : ActorMethod<[FileToken], ExternalBlob>,
  'getAllFiles' : ActorMethod<[], Array<FileInfoAdmin>>,
  'getCallerFiles' : ActorMethod<[], Array<FileInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatformCounts' : ActorMethod<[], PlatformCounts>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'renameFile' : ActorMethod<[FileId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'uploadFile' : ActorMethod<
    [string, bigint, ExternalBlob, [] | [Timestamp]],
    FileInfo
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];