/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileId = IDL.Nat;
export const FileToken = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const FileInfoAdmin = IDL.Record({
  'id' : FileId,
  'token' : FileToken,
  'name' : IDL.Text,
  'expiryTime' : IDL.Opt(Timestamp),
  'size' : IDL.Nat,
  'uploader' : IDL.Principal,
  'downloadCount' : IDL.Nat,
  'uploadTime' : Timestamp,
});
export const FileInfo = IDL.Record({
  'id' : FileId,
  'token' : FileToken,
  'name' : IDL.Text,
  'expiryTime' : IDL.Opt(Timestamp),
  'size' : IDL.Nat,
  'downloadCount' : IDL.Nat,
  'uploadTime' : Timestamp,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlatformCounts = IDL.Record({
  'totalFiles' : IDL.Nat,
  'totalBytes' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'downloadFile' : IDL.Func([FileToken], [ExternalBlob], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileInfoAdmin)], ['query']),
  'getCallerFiles' : IDL.Func([], [IDL.Vec(FileInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatformCounts' : IDL.Func([], [PlatformCounts], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'renameFile' : IDL.Func([FileId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Nat, ExternalBlob, IDL.Opt(Timestamp)],
      [FileInfo],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileId = IDL.Nat;
  const FileToken = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const FileInfoAdmin = IDL.Record({
    'id' : FileId,
    'token' : FileToken,
    'name' : IDL.Text,
    'expiryTime' : IDL.Opt(Timestamp),
    'size' : IDL.Nat,
    'uploader' : IDL.Principal,
    'downloadCount' : IDL.Nat,
    'uploadTime' : Timestamp,
  });
  const FileInfo = IDL.Record({
    'id' : FileId,
    'token' : FileToken,
    'name' : IDL.Text,
    'expiryTime' : IDL.Opt(Timestamp),
    'size' : IDL.Nat,
    'downloadCount' : IDL.Nat,
    'uploadTime' : Timestamp,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlatformCounts = IDL.Record({
    'totalFiles' : IDL.Nat,
    'totalBytes' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'downloadFile' : IDL.Func([FileToken], [ExternalBlob], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileInfoAdmin)], ['query']),
    'getCallerFiles' : IDL.Func([], [IDL.Vec(FileInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatformCounts' : IDL.Func([], [PlatformCounts], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'renameFile' : IDL.Func([FileId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Nat, ExternalBlob, IDL.Opt(Timestamp)],
        [FileInfo],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };