/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileId = IDL.Nat;
export const FileToken = IDL.Text;
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : FileId,
  'originalFilename' : IDL.Text,
  'createdAt' : Time,
  'byteSize' : IDL.Nat,
  'publicToken' : FileToken,
  'uploader' : IDL.Principal,
  'downloadCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CountStatistics = IDL.Record({
  'fileCount' : IDL.Nat,
  'fileSize' : IDL.Nat,
  'downloadCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'downloadFile' : IDL.Func(
      [FileToken],
      [
        IDL.Record({
          'originalFilename' : IDL.Text,
          'byteData' : IDL.Vec(IDL.Nat8),
        }),
      ],
      [],
    ),
  'finalizeUpload' : IDL.Func([FileId], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getCallerFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileMetadata' : IDL.Func([FileId], [FileMetadata], ['query']),
  'getFileToken' : IDL.Func([FileId], [FileToken], ['query']),
  'getFileUploader' : IDL.Func([FileId], [IDL.Principal], ['query']),
  'getPlatformCounts' : IDL.Func([], [CountStatistics], ['query']),
  'getTotalDownloadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initUpload' : IDL.Func([IDL.Text], [FileId], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadChunk' : IDL.Func([FileId, IDL.Vec(IDL.Nat8)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileId = IDL.Nat;
  const FileToken = IDL.Text;
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : FileId,
    'originalFilename' : IDL.Text,
    'createdAt' : Time,
    'byteSize' : IDL.Nat,
    'publicToken' : FileToken,
    'uploader' : IDL.Principal,
    'downloadCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CountStatistics = IDL.Record({
    'fileCount' : IDL.Nat,
    'fileSize' : IDL.Nat,
    'downloadCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'downloadFile' : IDL.Func(
        [FileToken],
        [
          IDL.Record({
            'originalFilename' : IDL.Text,
            'byteData' : IDL.Vec(IDL.Nat8),
          }),
        ],
        [],
      ),
    'finalizeUpload' : IDL.Func([FileId], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getCallerFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileMetadata' : IDL.Func([FileId], [FileMetadata], ['query']),
    'getFileToken' : IDL.Func([FileId], [FileToken], ['query']),
    'getFileUploader' : IDL.Func([FileId], [IDL.Principal], ['query']),
    'getPlatformCounts' : IDL.Func([], [CountStatistics], ['query']),
    'getTotalDownloadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initUpload' : IDL.Func([IDL.Text], [FileId], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadChunk' : IDL.Func([FileId, IDL.Vec(IDL.Nat8)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };