/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CountStatistics {
  'fileCount' : bigint,
  'fileSize' : bigint,
  'downloadCount' : bigint,
}
export type FileId = bigint;
export interface FileMetadata {
  'id' : FileId,
  'originalFilename' : string,
  'createdAt' : Time,
  'byteSize' : bigint,
  'publicToken' : FileToken,
  'uploader' : Principal,
  'downloadCount' : bigint,
}
export type FileToken = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'downloadFile' : ActorMethod<
    [FileToken],
    { 'originalFilename' : string, 'byteData' : Uint8Array }
  >,
  'finalizeUpload' : ActorMethod<[FileId], undefined>,
  'getAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getCallerFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileMetadata' : ActorMethod<[FileId], FileMetadata>,
  'getFileToken' : ActorMethod<[FileId], FileToken>,
  'getFileUploader' : ActorMethod<[FileId], Principal>,
  'getPlatformCounts' : ActorMethod<[], CountStatistics>,
  'getTotalDownloadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initUpload' : ActorMethod<[string], FileId>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadChunk' : ActorMethod<[FileId, Uint8Array], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];